export default [
	
	{
		name: 'Eka level',
		map:[
			"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
			"X                                      X",
			"X  s                                   X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X                                      X",
			"X         1      k         2           X",
			"X                                      X",
			"XXXXXXXXXXXXXXXXXDXXXXXmmXXXXXXXXXXXXXXX",
			]
	},



	{
		name: 'Level 1',
	    // Design the level. x = wall, o = coin, ! = lava.
	    map: [
	        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
	        'X                                      X',        
	        'X       c                c   s       c X',        
	        'X                                    c X',        
	        'X                     x      x       c X',        
	        'X         x                           cX',        
	        'X                                      X',        
	        'X            xxx     x                 X',        
	        'X      x             x           x x   X',        
	        'X      s   x       s                  sX',        
	        'X    xxxxxxxx      c     x    c        X',        
	        'X              x xxx               x   X',        
	        'X                            x    x    X',        
	        'X                  xxx           x     X',        
	        'X        c                             X',        
	        'X                     c  x             X',        
	        'X       x  x         x                 X',        
	        'X       x      x xx       xx x x       X',        
	        'X       xx                   c   c     X',        
	        'X          s                           X',        
	        'X         xxxxx  x x                   X',        
	        'X                      x               X',
	        'X                                   c  X',
	        'X                           x          X',
	        'X                              x       X',
	        'X           x        x  x  c  x  x     X',       
	        'X       c                              X',
	        'X           x    x               k     X',
	        'X  1  2                          xx    D',
	        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
	    ] 
	},
	{
		name: 'Level 2',
	    // Design the level. x = wall, o = coin, ! = lava.
	    map: [
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	        'x                                      x',        
	        'x       c                c   s       c x',        
	        'x                                    c x',        
	        'x                     x      x       c x',        
	        'x         x                           cx',        
	        'x                                      x',        
	        'x            xxx     x                 x',        
	        'x      x             x           x x   x',        
	        'x      s   x       s                   x',        
	        'x    xxxxxxxx      c     x    c        x',        
	        'x              x xxx               x   x',        
	        'x                            x    x    x',        
	        'x                  xxx           x     x',        
	        'x        c                             x',        
	        'x                     c  x             x',        
	        'x       x  x         x                 x',        
	        'x       x      x xx       xx x x       x',        
	        'x       xx                   c   c     x',        
	        'x          s                           x',        
	        'x         xxxxx  x x                   x',        
	        'x                      x               x',
	        'x                                   c  x',
	        'x                           x          x',
	        'x                              x       x',
	        'x           x        x  x  c  x  x     x',       
	        'x      c         k                     x',
	        'x           x    x                     x',
	        'x     1        2                 xx    D',
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	    ]
	},
	{
		name: 'Level 3',
	    // Design the level. x = wall, o = coin, ! = lava.
	    map: [
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	        'x                                      x',        
	        'x     k c                c   s       c x',        
	        'x                                    c x',        
	        'x         s           x      x       c x',        
	        'x         x                           cx',        
	        'x                                    s x',        
	        'x            xxx     x             s   x',        
	        'x      x             x           x x  sx',        
	        'x      s   x       s                   D',        
	        'x    xxxxxxxx      c     x    c       xx',        
	        'x              x xxx               x   x',        
	        'x                            x    x    x',        
	        'x                  xxx           x     x',        
	        'x        c                             x',        
	        'x                     c  x             x',        
	        'x       x  x         x          x      x',        
	        'x       x      x xx       xx x x       x',        
	        'x       xx                   c   c   x x',        
	        'x          s                           x',        
	        'x         xxxxx  x x                   x',        
	        'x                      x           x   x',
	        'x                                   c  x',
	        'x                           x          x',
	        'x                              x       x',
	        'x           x        x  x  c  x  x     x',       
	        'x      c    2    1                     x',
	        'x           x    x               s     x',
	        'x    s                           xx    x',
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	    ] 
	},			
];