export default [
	{
		name: 'Level 1',
	    // Design the level. x = wall, o = coin, ! = lava.
	    map: [
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	        'x                                      x',        
	        'x       c                c   s       c x',        
	        'x                                    c x',        
	        'x                     x      x       c x',        
	        'x         x                           cx',        
	        'x                                      x',        
	        'x            xxx     x                 x',        
	        'x      x             x           x x   x',        
	        'x      s   x       s                  sx',        
	        'x    xxxxxxxx      c     x    c        x',        
	        'x              x xxx               x   x',        
	        'x                            x    x    x',        
	        'x                  xxx           x     x',        
	        'x        c                             x',        
	        'x                     c  x             x',        
	        'x       x  x         x                 x',        
	        'x       x      x xx       xx x x       x',        
	        'x       xx                   c   c     x',        
	        'x          s                           x',        
	        'x         xxxxx  x x                   x',        
	        'x                      x               x',
	        'x                                   c  x',
	        'x                           x          x',
	        'x                              x       x',
	        'x           x        x  x  c  x  x     x',       
	        'x       c                              x',
	        'x           x    x               k     x',
	        'x  1  2                          xx    D',
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	    ] 
	},
	{
		name: 'Level 2',
	    // Design the level. x = wall, o = coin, ! = lava.
	    map: [
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	        'x                                      x',        
	        'x       c                c   s       c x',        
	        'x                                    c x',        
	        'x                     x      x       c x',        
	        'x         x                           cx',        
	        'x                                      x',        
	        'x            xxx     x                 x',        
	        'x      x             x           x x   x',        
	        'x      s   x       s                   x',        
	        'x    xxxxxxxx      c     x    c        x',        
	        'x              x xxx               x   x',        
	        'x                            x    x    x',        
	        'x                  xxx           x     x',        
	        'x        c                             x',        
	        'x                     c  x             x',        
	        'x       x  x         x                 x',        
	        'x       x      x xx       xx x x       x',        
	        'x       xx                   c   c     x',        
	        'x          s                           x',        
	        'x         xxxxx  x x                   x',        
	        'x                      x               x',
	        'x                                   c  x',
	        'x                           x          x',
	        'x                              x       x',
	        'x           x        x  x  c  x  x     x',       
	        'x      c         k                     x',
	        'x           x    x                     x',
	        'x     1        2                 xx    D',
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	    ]
	},
	{
		name: 'Level 3',
	    // Design the level. x = wall, o = coin, ! = lava.
	    map: [
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	        'x                                      x',        
	        'x     k c                c   s       c x',        
	        'x                                    c x',        
	        'x         s           x      x       c x',        
	        'x         x                           cx',        
	        'x                                    s x',        
	        'x            xxx     x             s   x',        
	        'x      x             x           x x  sx',        
	        'x      s   x       s                   D',        
	        'x    xxxxxxxx      c     x    c       xx',        
	        'x              x xxx               x   x',        
	        'x                            x    x    x',        
	        'x                  xxx           x     x',        
	        'x        c                             x',        
	        'x                     c  x             x',        
	        'x       x  x         x          x      x',        
	        'x       x      x xx       xx x x       x',        
	        'x       xx                   c   c   x x',        
	        'x          s                           x',        
	        'x         xxxxx  x x                   x',        
	        'x                      x           x   x',
	        'x                                   c  x',
	        'x                           x          x',
	        'x                              x       x',
	        'x           x        x  x  c  x  x     x',       
	        'x      c    2    1                     x',
	        'x           x    x               s     x',
	        'x    s                           xx    x',
	        'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	    ] 
	},			
];